name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install dependencies
      run: ./scripts/install-dependencies.sh

    - name: Build
      run: go build -v ./...

    - name: Test
      run: LD_LIBRARY_PATH="/usr/local/lib/" go test -v ./...
